Limelight subsystem
robototes/Crescendo2024 pull request #16
Opened 2024-01-23 04:05 UTC by Jetblackdragon

Added limelight subsystem with constructer and getter methods.

2024-01-27 22:02 UTC, jamesdooley4 requested changes

2024-01-27 22:02 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +	NetworkTable networkTable;
Should be `final`

2024-01-27 22:02 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +				new Pose2d(currentPose.getX() + targetY, currentPose.getY() + targetX, targetHeading);
? This is adding getX() to targetY, which seems odd. If that's intended, please add a comment explaining why.

2024-01-27 23:43 UTC, TAKBS2412 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +	NetworkTable networkTable;
(and `private`)

2024-02-21 03:15 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LEDSubsystem.java
? the LED subsystem is empty.

2024-02-21 03:22 UTC, bobtseattle requested changes

2024-02-21 03:22 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +public class VisionSubsystem extends SubsystemBase {
This should be LimelightSubsystem not VisionSubsystem?

2024-02-21 03:22 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +	public boolean hasTargets() {
Assuming this is just for testing and there will be a method called (or field to return) instead?

2024-02-24 02:46 UTC, TAKBS2412 commented
Can we close this PR since no files have been changed in it?

2024-02-24 18:55 UTC, closed without merging