LEDSubsystem
robototes/Crescendo2024 pull request #35
Opened 2024-02-09 02:48 UTC by Jetblackdragon

2024-02-16 02:08 UTC, jamesdooley4 requested changes

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LEDSubsystem.java
> +	}
Should be private, as nothing outside the class should call this

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LEDSubsystem.java
> +		blinkin.setSpeed(RED_LED_COLOR); // sets to red
Would be better to use `setPulseTimeMicroseconds​` instead of `setSpeed`, to not depend on the PWM output range (see https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/PWM.html )

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LEDSubsystem.java
> +    private static final double YELLOW_LED_COLOR = 0.69;
See the bottom of https://www.revrobotics.com/content/docs/REV-11-1105-UM.pdf for th pulse width values to use instead of the speed values here (which only work if the PWM port was configured to be used with a SPARK MAX somehow).

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LEDSubsystem.java
> +	}
Or update this to take an enum as the parameter that the class internally converts to a pulse width value for the color or pattern to use.

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/commands/drivebase/DriveCommand.java
Please delete this empty file

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +	public static final double GOAL_DISTANCE_FROM_CUBE = 0.3;
Should delete since these aren't used in this year's game.

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +
That's a dynamic IP address that will change once the robot is connected to the FMS. This needs to not conflict with [AprilTag PR](https://github.com/robototes/Crescendo2024/pull/41) and be between 10.TE.AM.5 (or .6, if the driver station is statically set to .5) to 10.TE.AM.20 (inclusive) per https://docs.wpilib.org/en/stable/docs/networking/networking-introduction/ip-configurations.html#on-the-field-static-configuration
Anything above .20 might be allocated elsewhere by the FMS. Typically the LL is .10

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +		networkTable.getEntry("pipeline").setNumber(2);
Should be private, as nothing outside the class should call it

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +
If this is important to keep, please add a comment explaining why. If not, please delete.

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +
Consider returning `Measure<Distance>` and using `Inches.of(...)` below so the caller can use any units it wants.

2024-02-16 02:08 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystems/LimelightSubsystem.java
> +			System.out.println("has targets");
Please delete (or comment) the println before completing the PR

2024-02-21 03:09 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/commands/drivebase/DriveCommand.java
The empty DriveCommand.java is still there...

2024-02-21 03:13 UTC, Jetblackdragon commented on src/main/java/frc/team2412/robot/commands/drivebase/DriveCommand.java
fixed

2024-02-21 03:14 UTC, closed without merging