Shuffleboard Debug Mode vs Non Debug Mode
robototes/Crescendo2024 pull request #78
Opened 2024-03-01 00:22 UTC by stewluj

Logs more or less depending whether or not debug mode is true

2024-03-01 02:40 UTC, TAKBS2412 commented on src/main/java/frc/team2412/robot/subsystems/IntakeSubsystem.java
> +					.addDouble("Index Motor Temp", () -> feederMotor.getMotorTemperature())
This one is named Index motor temp, but uses the feeder motor...

2024-03-01 03:55 UTC, bobtseattle requested changes, later dismissed
Noting a mismatch between the label and data.

2024-03-01 03:55 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/subsystems/LauncherSubsystem.java
> +					.addDouble("Top FlyWheel Temp", () -> launcherBottomMotor.getMotorTemperature());
Labeled as top but displays bottom motor.

2024-03-18 09:27 UTC, TAKBS2412 approved these changes, later dismissed

2024-03-18 09:28 UTC, TAKBS2412 commented
Approved (pending formatting issues).

2024-03-19 01:58 UTC, bobtseattle approved these changes
LGTM

2024-03-19 02:00 UTC, merged

2024-03-19 03:32 UTC, KangarooKoala commented on src/main/java/frc/team2412/robot/subsystems/LauncherSubsystem.java
> +					.addDouble("Top FlyWheel Temp", () -> launcherTopMotor.getMotorTemperature());
Have we tested the placement of these? Bottom previously had `.withPosition(0, 3)` and `.withSize(2, 1)` and top previously had `.withPosition(2, 3)` and `.withSize(2, 1)`, but without those I'm worried they will be assigned a spot that overlaps with something else.